line-length = 120
exclude = [
  "tests",
  "build",
]

[lint]
select = ["ALL"]
ignore = [
  "ANN204", "ANN401",
  "D100", "D203", "D211", "D212", "D213", "D413",
  "FA102",
  "RUF001", "RUF002", "RUF003",
  "EM101", "EM102",
  "N812", "N815", "N999",
  "PTH100", "PTH118", "PTH120", "PTH123",
  "PERF203",
  "COM812",
  "TRY003",
]
